Models/ErrorViewModel.cs
namespace UpscaleTechnicalTest.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/TodoModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UpscaleTechnicalTest.Models;

public class TodoModel
{
    [Key, Column(name: "Id"), DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }
    [Required]
    [StringLength(150)]
    public string Title { get; set; }
    [Required]
    [StringLength(750)]
    public string Description { get; set; }
    [Required]
    [StringLength(50)]
    public string Scope { get; set; }
    [Required]
    public int Priority { get; set; }
    [Required]
    public DateTime Deadline { get; set; }
    [Display(Name = "Is Completed?")]
    public bool? IsCompleted { get; set; }
    [StringLength(250)]
    public string EmailNotification { get; set; } = string.Empty;
    public bool IsNotificationSend { get; set; } = false;
    [Display(Name = "Created Date")]
    [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy HH:mm}")]
    public DateTime CreatedDate { get; set; }
    [Display(Name = "Updated Date")]
    [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy HH:mm}")]
    public DateTime? UpdatedDate { get; set; }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using UpscaleTechnicalTest.Models;

namespace UpscaleTechnicalTest.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [Authorize]
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/TodoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using UpscaleTechnicalTest.Models;
using UpscaleTechnicalTest.Services;

namespace UpscaleTechnicalTest.Controllers;

[Authorize]
public class TodoController : Controller
{
    private readonly ITodoService _service;
    private readonly UserManager<IdentityUser> _userManager;
    private readonly SignInManager<IdentityUser> _signInManager;
    public TodoController(ITodoService service, SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager)
    {
        _service = service;
        _signInManager = signInManager;
        _userManager = userManager;
    }

    // GET: Todo
    public async Task<IActionResult> Index()
    {
        var getList = await _service.List();
        if (getList.Error.status)
            return Problem(getList.Error.error);

        return View(getList.Successful.data);
    }

    // GET: Todo/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
            return NotFound();

        var get = await _service.Get(id);
        if (get.Error.status)
            if (get.Error.error == "Data not found")
                return NotFound();
            else
                return Problem(get.Error.error);

        return View(get.Successful.data);
    }

    // GET: Todo/Create
    public IActionResult Create()
    {
        return View();
    }

    // POST: Todo/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Title,Description,Scope,Priority,Deadline,IsCompleted")] TodoModel todoModel)
    {
        if (ModelState.IsValid)
        {
            var user = await _userManager.FindByNameAsync(User.Identity?.Name!);
            todoModel.EmailNotification = user?.Email!;

            var save = await _service.Save(todoModel);
            if (save.Error.status)
                if (save.Error.error == "Data not found")
                    return NotFound();
                else
                    return Problem(save.Error.error);

            return RedirectToAction(nameof(Index));
        }
        return View(todoModel);
    }

    // GET: Todo/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
            return NotFound();

        var get = await _service.Get(id);
        if (get.Error.status)
            if (get.Error.error == "Data not found")
                return NotFound();
            else
                return Problem(get.Error.error);

        return View(get.Successful.data);
    }

    // POST: Todo/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Scope,Priority,Deadline,IsCompleted")] TodoModel todoModel)
    {
        if (id != todoModel.Id)
            return NotFound();

        if (ModelState.IsValid)
        {
            var update = await _service.Update(todoModel);
            if (update.Error.status)
                if (update.Error.error == "Data not found")
                    return NotFound();
                else
                    return Problem(update.Error.error);
            return RedirectToAction(nameof(Index));
        }
        return View(todoModel);
    }

    // GET: Todo/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
            return NotFound();

        var get = await _service.Get(id);
        if (get.Error.status)
            if (get.Error.error == "Data not found")
                return NotFound();
            else
                return Problem(get.Error.error);

        return View(get.Successful.data);
    }

    // POST: Todo/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var delete = await _service.Delete(id);
        if (delete.Error.status)
            if (delete.Error.error == "Data not found")
                return NotFound();
            else
                return Problem(delete.Error.error);

        return RedirectToAction(nameof(Index));
    }

    // GET: Todo/MarkAsCompleted/5
    public async Task<IActionResult> MarkAsCompleted(int? id)
    {
        if (id == null)
            return NotFound();

        var get = await _service.Get(id);
        if (get.Error.status)
            if (get.Error.error == "Data not found")
                return NotFound();
            else
                return Problem(get.Error.error);

        return View(get.Successful.data);
    }

    // POST: Todo/Delete/5
    [HttpPost, ActionName("MarkAsCompleted")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> MarkAsCompletedConfirmed(int id)
    {
        var markAsCompleted = await _service.MarkAsCompleted(id);
        if (markAsCompleted.Error.status)
            if (markAsCompleted.Error.error == "Data not found")
                return NotFound();
            else
                return Problem(markAsCompleted.Error.error);

        return RedirectToAction(nameof(Index));
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UpscaleTechnicalTest</title>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-table/bootstrap-table.min.js"></script>
    <script src="~/lib/bootstrap-table/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-table/bootstrap-table.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-table/extensions/filter-control/bootstrap-table-filter-control.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UpscaleTechnicalTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UpscaleTechnicalTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Todo" asp-action="Index">Todo</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UpscaleTechnicalTest
        </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Todo/Create.cshtml
@model UpscaleTechnicalTest.Models.TodoModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Add New</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Scope" class="control-label"></label>
                <select asp-for="Scope" class="form-control">
                    <option value="IT">IT</option>
                    <option value="Accounting">Accounting</option>
                    <option value="Operation">Operation</option>
                    <option value="Driver">Driver</option>
                </select>
                <span asp-validation-for="Scope" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
                <select asp-for="Priority" class="form-control">
                    <option value="0">0</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                </select>
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsCompleted" class="control-label"></label>
                <select asp-for="IsCompleted" class="form-control">
                    <option value="">Not Set</option>
                    <option value="false">False</option>
                    <option value="true">True</option>
                </select>
                <span asp-validation-for="IsCompleted" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Todo/Delete.cshtml
@model UpscaleTechnicalTest.Models.TodoModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>
<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Scope)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Scope)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class = "col-sm-10">
            @Model.Deadline.ToString("dd-MMM-yyyy HH:mm")
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>
        <dd class = "col-sm-10">
            @(Model.IsCompleted is null ? "Not Set" : Model.IsCompleted.ToString())
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Todo/Details.cshtml
@model UpscaleTechnicalTest.Models.TodoModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Scope)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Scope)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class="col-sm-10">
            @Model.Deadline.ToString("dd-MMM-yyyy HH:mm")
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>
        <dd class="col-sm-10">
            @(Model.IsCompleted is null ? "Not Set" : Model.IsCompleted.ToString())
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Todo/Edit.cshtml
@model UpscaleTechnicalTest.Models.TodoModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Scope" class="control-label"></label>
                <select asp-for="Scope" class="form-control">
                    <option value="IT">IT</option>
                    <option value="Accounting">Accounting</option>
                    <option value="Operation">Operation</option>
                    <option value="Driver">Driver</option>
                </select>
                <span asp-validation-for="Scope" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Priority" class="control-label"></label>
                <select asp-for="Priority" class="form-control">
                    <option value="0">0</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                </select>
                <span asp-validation-for="Priority" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />
                <span asp-validation-for="Deadline" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IsCompleted" class="control-label"></label>
                <select asp-for="IsCompleted" class="form-control">
                    <option value="">Not Set</option>
                    <option value="false">False</option>
                    <option value="true">True</option>
                </select>
                <span asp-validation-for="IsCompleted" class="text-danger"></span>
            </div>
            <div class="form-group mt-2">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Todo/Index.cshtml
@model IEnumerable<UpscaleTechnicalTest.Models.TodoModel>

@{
    ViewData["Title"] = "Todo List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create">Add New</a>
</p>

<table id="table" class="table table-striped" data-search="true" data-sortable="true" data-sort-name="0" data-sort-order="asc" data-pagination="true" data-page-size="5" data-filter-control="true" data-show-search-clear-button="true">
    <thead>
        <tr>
            <th data-sortable="true">
                #
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.Scope)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.Priority)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.Deadline)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.IsCompleted)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th data-sortable="true">
                @Html.DisplayNameFor(model => model.UpdatedDate)
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @{
            var itemCount = 1;
            foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => itemCount)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Scope)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Priority)
                    </td>
                    <td>
                        @item.Deadline.ToString("dd-MMM-yyyy HH:mm")
                    </td>
                    <td>
                        @(item.IsCompleted is null ? "Not Set" : item.IsCompleted.ToString())
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UpdatedDate)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        @{
                            if (item.IsCompleted is null || !item.IsCompleted.Value){
                                <text>
                                    <a asp-action="MarkAsCompleted" asp-route-id="@item.Id">Mark As Completed</a> |
                                </text>
                            }
                        }
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
                itemCount = itemCount + 1;
            }
        }
    </tbody>
</table>

<script>
    $(function () {
        $("#table").bootstrapTable();
    });
</script>

Views/Todo/MarkAsCompleted.cshtml
@model UpscaleTechnicalTest.Models.TodoModel

@{
    ViewData["Title"] = "Mark as Completed";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Mark as Completed</h1>
<h3>Are you sure you want to mark this task as completed?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Scope)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Scope)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Priority)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Priority)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Deadline)
        </dt>
        <dd class = "col-sm-10">
            @Model.Deadline.ToString("dd-MMM-yyyy HH:mm")
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsCompleted)
        </dt>
        <dd class = "col-sm-10">
            @(Model.IsCompleted is null ? "Not Set" : Model.IsCompleted.ToString())
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdatedDate)
        </dd>
    </dl>
    
    <form asp-action="MarkAsCompleted">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Confirm" class="btn btn-success" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>